name: GitHub action kernel builder

on:
  workflow_dispatch:
    inputs:
      REPO_URL:
        description: 'REPO_URL'
        required: true
        default: 'https://Sa-Sajjad:$ght@github.com/Sa-Sajjad/kernel_xiaomi_lavender-neko'
      DEFAULT_BRANCH:
        description: 'DEFAULT_BRANCH'
        required: true
        default: 'try'
      BUILD_COMMAND:
        description: 'BUILD_COMMAND'
        required: true
        default: 'bash scripts/kbuild.sh'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      chat_id: 1278600516
      token: ${{ secrets.TOKEN }}
      ght: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: COMPILING 
        run: |
          git config --global user.name "Sa-Sajjad"
          git config --global user.email "sqsa93103@gmail.com"
          git config --global color.ui false
          git clone --depth=1 ${{ github.event.inputs.REPO_URL }} -b ${{ github.event.inputs.DEFAULT_BRANCH }} snx && cd snx
          ${{ github.event.inputs.BUILD_COMMAND }}
          
